security:
  oauth2:
    client:
      client-id: bd1c0a783ccdd1c9b9e4
      client-secret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      authentication-scheme: form
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false