version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: dataflow-mysql
    volumes:
      - /home/docker/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dataflow
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  dataflow-server:
    image: springcloud/spring-cloud-dataflow-server:${DATAFLOW_VERSION:?DATAFLOW_VERSION is not set!}
    container_name: dataflow-server
    ports:
      - 9393:9393
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dataflow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - spring.cloud.dataflow.applicationProperties.stream.spring.rabbitmq.host=rabbitmq
    depends_on:
      - rabbitmq
      - redis
      - mysql
    entrypoint: "./wait-for-it.sh mysql:3306 -- java -jar /maven/spring-cloud-dataflow-server.jar"

#  app-import:
#    image: springcloud/openjdk:2.0.0.RELEASE
#    container_name: dataflow-app-import
#    depends_on:
#      - dataflow-server
#    command: >
#      /bin/sh -c "
#        ./wait-for-it.sh -t 180 dataflow-server:9393;
#        wget -qO- 'http://dataflow-server:9393/apps' --post-data='uri=${STREAM_APPS_URI:-https://dataflow.spring.io/rabbitmq-maven-latest&force=true}';
#        echo 'Stream apps imported'
#        wget -qO- 'http://dataflow-server:9393/apps' --post-data='uri=${TASK_APPS_URI:-https://dataflow.spring.io/task-maven-latest&force=true}';
#        echo 'Task apps imported'"
