---
server:
  port: 8888
spring:
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Suamo/spring-cloud
          searchPaths: configurations,configurations/station*
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/Suamo/spring-cloud
              searchPaths: preformance,preformance/station*